name: Run Orbs Regression Suite

on:
  push:
    branches: [ main ]

  pull_request:
    types: [ closed ]
    branches: [ main ]

  workflow_dispatch:

jobs:
  regression:
    permissions:
      checks: write
      contents: read

    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Orbs CLI
        run: pip install orbs-cli

      - name: Run Regression Suite
        env:
          headless: true
        run: |
          orbs run testsuites/login_cura.yml

      - name: Publish JUnit Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: reports/**/*.xml
          fail_on_failure: true
          detailed_summary: true

      - name: Upload Orbs Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: orbs-test-report
          path: reports/
